export { default as About } from "./About";
export { default as Auth } from "./Auth";
export { default as Companies } from "./Companies";
export { default as CompanyProfile } from "./CompanyProfile";
export { default as FindJobs } from "./FindJobs";
export { default as JobDetails } from "./JobDetails";
export { default as UploadJob } from "./UploadJob";
export { default as UserProfile } from "./UserProfile";
export { default as Applicants } from "./Applicants";
